"""initial schema

Revision ID: bb3223b67ef5
Revises: 
Create Date: 2026-06-14 08:29:22.010554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb3223b67ef5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'prefix',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('api_keys', 'label',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('api_keys', 'scopes',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index(op.f('idx_api_keys_hash'), table_name='api_keys', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('idx_api_keys_org'), table_name='api_keys')
    op.alter_column('audit_events', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('audit_events', 'resource_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_events', 'resource_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_events', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_events', 'chain_anchor_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_audit_action'), table_name='audit_events')
    op.drop_index(op.f('idx_audit_actor'), table_name='audit_events')
    op.drop_index(op.f('idx_audit_org'), table_name='audit_events')
    op.drop_index(op.f('idx_audit_resource'), table_name='audit_events')
    op.alter_column('consensus_results', 'overall_risk',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('consensus_results', 'chain_tx_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_email_verify_user'), table_name='email_verifications')
    op.alter_column('findings', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('findings', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('findings', 'consensus_severity',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('findings', 'consensus_verdict',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('findings', 'content_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('findings', 'chain_finding_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_findings_category'), table_name='findings')
    op.drop_index(op.f('idx_findings_review'), table_name='findings')
    op.drop_index(op.f('idx_findings_severity'), table_name='findings', postgresql_where="(consensus_verdict = 'confirmed'::text)")
    op.alter_column('github_installations', 'account_login',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('github_installations', 'account_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('github_installations', 'events',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.drop_index(op.f('idx_gh_install_id'), table_name='github_installations')
    op.drop_index(op.f('idx_gh_install_org'), table_name='github_installations')
    op.create_unique_constraint(None, 'github_installations', ['installation_id'])
    op.alter_column('org_members', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::text"))
    op.drop_index(op.f('idx_org_members_unique'), table_name='org_members')
    op.drop_index(op.f('idx_org_members_user'), table_name='org_members')
    op.alter_column('organizations', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('organizations', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('organizations', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'team'::text"))
    op.alter_column('organizations', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('organizations', 'plan',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::text"))
    op.drop_index(op.f('idx_orgs_slug'), table_name='organizations')
    op.create_unique_constraint(None, 'organizations', ['slug'])
    op.drop_index(op.f('idx_pw_reset_user'), table_name='password_resets')
    op.alter_column('repositories', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('repositories', 'default_branch',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False,
               existing_server_default=sa.text("'main'::text"))
    op.alter_column('repositories', 'primary_language',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_repos_gh_id'), table_name='repositories', postgresql_where='(github_repo_id IS NOT NULL)')
    op.drop_index(op.f('idx_repos_org'), table_name='repositories')
    op.alter_column('review_files', 'file_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('review_files', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('review_files', 'content_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('review_files', 'blob_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_review_files_path'), table_name='review_files')
    op.drop_index(op.f('idx_review_files_review'), table_name='review_files')
    op.alter_column('reviews', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('reviews', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('reviews', 'commit_sha',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reviews', 'branch',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reviews', 'code_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('reviews', 'blob_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reviews', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reviews', 'languages',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reviews', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('reviews', 'chain_tx_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('reviews', 'chain_review_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_reviews_created_by'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_org'), table_name='reviews')
    op.drop_index(op.f('idx_reviews_repo'), table_name='reviews', postgresql_where='(repo_id IS NOT NULL)')
    op.drop_index(op.f('idx_reviews_status'), table_name='reviews', postgresql_where="(status <> ALL (ARRAY['done'::text, 'failed'::text]))")
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_sessions_expires'), table_name='sessions', postgresql_where='(revoked_at IS NULL)')
    op.drop_index(op.f('idx_sessions_user'), table_name='sessions')
    op.alter_column('usage_records', 'metric',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_usage_org_period'), table_name='usage_records')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email_normalized',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('users', 'display_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_users_created'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email_normalized'])
    op.alter_column('validator_votes', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('validator_votes', 'exploitability',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('validator_votes', 'reasoning_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_votes_finding'), table_name='validator_votes')
    op.drop_index(op.f('idx_votes_unique'), table_name='validator_votes')
    op.alter_column('wallets', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_wallets_address'), table_name='wallets')
    op.create_unique_constraint(None, 'wallets', ['address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='unique')
    op.create_index(op.f('idx_wallets_address'), 'wallets', ['address'], unique=True)
    op.alter_column('wallets', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_votes_unique'), 'validator_votes', ['finding_id', 'validator_index'], unique=True)
    op.create_index(op.f('idx_votes_finding'), 'validator_votes', ['finding_id'], unique=False)
    op.alter_column('validator_votes', 'reasoning_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('validator_votes', 'exploitability',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('validator_votes', 'severity',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('idx_users_email'), 'users', ['email_normalized'], unique=True)
    op.create_index(op.f('idx_users_created'), 'users', ['created_at'], unique=False)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email_normalized',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_usage_org_period'), 'usage_records', ['org_id', 'period_start'], unique=False)
    op.alter_column('usage_records', 'metric',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_sessions_user'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_expires'), 'sessions', ['expires_at'], unique=False, postgresql_where='(revoked_at IS NULL)')
    op.alter_column('sessions', 'ip_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_reviews_status'), 'reviews', ['status'], unique=False, postgresql_where="(status <> ALL (ARRAY['done'::text, 'failed'::text]))")
    op.create_index(op.f('idx_reviews_repo'), 'reviews', ['repo_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(repo_id IS NOT NULL)')
    op.create_index(op.f('idx_reviews_org'), 'reviews', ['org_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_reviews_created_by'), 'reviews', ['created_by'], unique=False)
    op.alter_column('reviews', 'chain_review_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reviews', 'chain_tx_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reviews', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('reviews', 'languages',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('reviews', 'language',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reviews', 'blob_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reviews', 'code_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('reviews', 'branch',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reviews', 'commit_sha',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reviews', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('reviews', 'source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_review_files_review'), 'review_files', ['review_id'], unique=False)
    op.create_index(op.f('idx_review_files_path'), 'review_files', ['review_id', 'file_path'], unique=True)
    op.alter_column('review_files', 'blob_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('review_files', 'content_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('review_files', 'language',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('review_files', 'file_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_repos_org'), 'repositories', ['org_id'], unique=False)
    op.create_index(op.f('idx_repos_gh_id'), 'repositories', ['github_repo_id'], unique=True, postgresql_where='(github_repo_id IS NOT NULL)')
    op.alter_column('repositories', 'primary_language',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('repositories', 'default_branch',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'main'::text"))
    op.alter_column('repositories', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_pw_reset_user'), 'password_resets', ['user_id'], unique=False)
    op.drop_constraint(None, 'organizations', type_='unique')
    op.create_index(op.f('idx_orgs_slug'), 'organizations', ['slug'], unique=True)
    op.alter_column('organizations', 'plan',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'free'::text"))
    op.alter_column('organizations', 'avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('organizations', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'team'::text"))
    op.alter_column('organizations', 'slug',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('organizations', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_org_members_user'), 'org_members', ['user_id'], unique=False)
    op.create_index(op.f('idx_org_members_unique'), 'org_members', ['org_id', 'user_id'], unique=True)
    op.alter_column('org_members', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'viewer'::text"))
    op.drop_constraint(None, 'github_installations', type_='unique')
    op.create_index(op.f('idx_gh_install_org'), 'github_installations', ['org_id'], unique=False)
    op.create_index(op.f('idx_gh_install_id'), 'github_installations', ['installation_id'], unique=True)
    op.alter_column('github_installations', 'events',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('github_installations', 'account_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('github_installations', 'account_login',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_findings_severity'), 'findings', ['consensus_severity'], unique=False, postgresql_where="(consensus_verdict = 'confirmed'::text)")
    op.create_index(op.f('idx_findings_review'), 'findings', ['review_id'], unique=False)
    op.create_index(op.f('idx_findings_category'), 'findings', ['category', 'review_id'], unique=False)
    op.alter_column('findings', 'chain_finding_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('findings', 'content_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('findings', 'consensus_verdict',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('findings', 'consensus_severity',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('findings', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('findings', 'category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_email_verify_user'), 'email_verifications', ['user_id'], unique=False)
    op.alter_column('consensus_results', 'chain_tx_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('consensus_results', 'overall_risk',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_audit_resource'), 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('idx_audit_org'), 'audit_events', ['org_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_actor'), 'audit_events', ['actor_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_audit_action'), 'audit_events', ['action', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('audit_events', 'chain_anchor_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_events', 'ip_address',
               existing_type=sa.String(),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.alter_column('audit_events', 'resource_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_events', 'resource_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_events', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_api_keys_org'), 'api_keys', ['org_id'], unique=False)
    op.create_index(op.f('idx_api_keys_hash'), 'api_keys', ['key_hash'], unique=False, postgresql_where='(revoked_at IS NULL)')
    op.alter_column('api_keys', 'scopes',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('api_keys', 'label',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('api_keys', 'prefix',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
